import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';

export const generateAndSharePDF = async (htmlContent: string, fileName: string) => {
  try {
    // 1. HTML ko PDF mein convert karein
    const { uri } = await Print.printToFileAsync({ 
      html: htmlContent,
      base64: false 
    });

    // 2. PDF ko share/save karne ka option dein
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { 
        mimeType: 'application/pdf', 
        dialogTitle: `Save or Share ${fileName}` 
      });
    } else {
      Alert.alert('Error', 'Sharing is not available on this device');
    }
  } catch (error) {
    console.error('PDF Generation Error:', error);
    Alert.alert('Error', 'Failed to generate PDF. Please try again.');
  }
};

// Helper function jo data ko HTML Table mein badalta hai
export const createAttendanceHTML = (title: string, records: any[], userName: string) => {
  const rows = records.map((record: any) => `
    <tr>
      <td>${record.date || 'N/A'}</td>
      <td>${record.dept || record.department || 'N/A'}</td>
      <td>${record.sem || 'N/A'}</td>
      <td>Period ${record.period || 'N/A'}</td>
      <td>${record.teacher || 'N/A'}</td>
      <td>${record.code || 'N/A'}</td>
      <td style="color: ${record.status?.toLowerCase() === 'present' ? 'green' : 'red'}; font-weight: bold;">
        ${record.status || 'N/A'}
      </td>
      <td>${record.substitute || '-'}</td>
    </tr>
  `).join('');

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; color: #333; }
          h2 { color: #1A237E; text-align: center; }
          p { text-align: center; color: #666; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #1A237E; color: white; }
          tr:nth-child(even) { background-color: #f9f9f9; }
        </style>
      </head>
      <body>
        <h2>${title}</h2>
        <p>Generated by: ${userName} | Date: ${new Date().toLocaleDateString()}</p>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Department</th>
              <th>Semester</th>
              <th>Period</th>
              <th>Teacher</th>
              <th>Subject</th>
              <th>Status</th>
              <th>Substitute</th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
        </table>
      </body>
    </html>
  `;
};